// Copyright Tribulation 66. All Rights Reserved.

#include "UI/Style/T66Style.h"
#include "UI/Style/T66ButtonVisuals.h"
#include "T66.h"

#include "Engine/Texture2D.h"
#include "HAL/IConsoleManager.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "Misc/Paths.h"
#include "UObject/StrongObjectPtr.h"
#include "Styling/CoreStyle.h"
#include "Styling/SlateStyleRegistry.h"
#include "Styling/SlateTypes.h"
#include "Brushes/SlateRoundedBoxBrush.h"
#include "Brushes/SlateColorBrush.h"
#include "Widgets/Images/SImage.h"
#include "Widgets/Layout/SBox.h"
#include "Layout/Visibility.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Input/SComboButton.h"
#include "Widgets/SOverlay.h"
#include "Widgets/Text/STextBlock.h"
#include "Fonts/CompositeFont.h"
#include "Blueprint/UserWidget.h"
#include "TimerManager.h"

TSharedPtr<FSlateStyleSet> FT66Style::StyleInstance;

// --- Colors (dark presentation) ---
FLinearColor FT66Style::Tokens::Bg(0.08f, 0.08f, 0.10f, 1.0f);
FLinearColor FT66Style::Tokens::Panel(0.0f, 0.0f, 0.0f, 1.0f);
FLinearColor FT66Style::Tokens::Panel2(0.0f, 0.0f, 0.0f, 1.0f);
FLinearColor FT66Style::Tokens::Stroke(0.18f, 0.18f, 0.20f, 1.0f);
FLinearColor FT66Style::Tokens::Scrim(0.f, 0.f, 0.f, 0.70f);
FLinearColor FT66Style::Tokens::Text(1.0f, 1.0f, 1.0f, 1.0f);
FLinearColor FT66Style::Tokens::TextMuted(0.75f, 0.75f, 0.75f, 1.0f);
FLinearColor FT66Style::Tokens::Accent(0.0f, 0.0f, 0.0f, 1.0f);
FLinearColor FT66Style::Tokens::Accent2(0.0f, 0.0f, 0.0f, 1.0f);
FLinearColor FT66Style::Tokens::Danger(0.95f, 0.15f, 0.15f, 1.0f);
FLinearColor FT66Style::Tokens::Success(0.20f, 0.80f, 0.35f, 1.0f);
FLinearColor FT66Style::Tokens::Border(1.0f, 1.0f, 1.0f, 1.0f);
const FMargin FT66Style::Tokens::ButtonPadding(12.f, 4.f);
const FMargin FT66Style::Tokens::ButtonPaddingPressed(12.f, 5.f, 12.f, 3.f);

namespace
{
	// Keep recent old style sets alive so existing Slate widgets' brush/style
	// raw pointers remain valid until the UI is rebuilt with fresh widgets.
	// Without this, calling StyleInstance.Reset() would free the FButtonStyle and
	// FSlateBrush objects that live Slate widgets still reference, causing access violations.
	// We keep up to 4 old sets to handle rapid font cycling and UI rebuilds.
	static TArray<TSharedPtr<FSlateStyleSet>> GPreviousStyleSets;
	static constexpr int32 GMaxPreviousStyleSets = 4;

	void RetainOldStyleSet(TSharedPtr<FSlateStyleSet>&& OldSet)
	{
		if (OldSet.IsValid())
		{
			GPreviousStyleSets.Add(MoveTemp(OldSet));
			while (GPreviousStyleSets.Num() > GMaxPreviousStyleSets)
			{
				GPreviousStyleSets.RemoveAt(0);
			}
		}
	}

	// Button textures: dark set with bevel, gloss, and border baked in.
	// Generated by Scripts/GenerateButtonTextures.py, imported by Scripts/ImportButtonTextures.py.
	// Loaded once and kept alive so FSlateBrush resource pointers remain valid.
	static TObjectPtr<UTexture2D> GBtnDarkN = nullptr;
	static TObjectPtr<UTexture2D> GBtnDarkH = nullptr;
	static TObjectPtr<UTexture2D> GBtnDarkP = nullptr;

	static bool HasButtonTextures()
	{
		return GBtnDarkN && GBtnDarkH && GBtnDarkP;
	}

	static void GetButtonTextures(UTexture2D*& OutN, UTexture2D*& OutH, UTexture2D*& OutP)
	{
		OutN = GBtnDarkN;
		OutH = GBtnDarkH;
		OutP = GBtnDarkP;
	}

	static FSlateBrush MakeButtonTextureBrush(UTexture2D* Tex)
	{
		FSlateBrush Brush;
		Brush.DrawAs = ESlateBrushDrawType::Image;
		Brush.Tiling = ESlateBrushTileType::NoTile;
		Brush.SetResourceObject(Tex);
		Brush.TintColor = FSlateColor(FLinearColor::White);  // texture has final colors baked in
		Brush.ImageSize = FVector2D(512.f, 128.f);
		return Brush;
	}

	static void LoadButtonTexturesOnce()
	{
		// Only load once — textures persist for the lifetime of the process.
		if (GBtnDarkN) return;
		auto Load = [](const TCHAR* Path) -> UTexture2D* {
			UTexture2D* T = LoadObject<UTexture2D>(nullptr, Path);
			UE_LOG(LogTemp, Log, TEXT("[T66Style] Load button tex %s -> %s"), Path, T ? TEXT("OK") : TEXT("MISS"));
			return T;
		};
		GBtnDarkN  = Load(TEXT("/Game/UI/Assets/ButtonDark_N.ButtonDark_N"));
		GBtnDarkH  = Load(TEXT("/Game/UI/Assets/ButtonDark_H.ButtonDark_H"));
		GBtnDarkP  = Load(TEXT("/Game/UI/Assets/ButtonDark_P.ButtonDark_P"));
	}

	// Panel texture: dark panel with bevel, gloss, and border baked in.
	static TObjectPtr<UTexture2D> GPanelDark = nullptr;
	static TObjectPtr<UMaterialInterface> GButtonGlowMaterial = nullptr;
	static bool bCheckedButtonGlowMaterial = false;

	static bool GPanelTexturesAvailable()
	{
		return GPanelDark != nullptr;
	}

	struct FT66ButtonGlowState
	{
		float Intensity = 0.f;
		FLinearColor Color = FLinearColor::White;
		TSharedPtr<FSlateBrush> Brush;
		TStrongObjectPtr<UMaterialInstanceDynamic> Material;
	};

	static UMaterialInterface* GetButtonGlowMaterial()
	{
		if (!bCheckedButtonGlowMaterial)
		{
			bCheckedButtonGlowMaterial = true;
			GButtonGlowMaterial = LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/UI/Materials/M_UI_Glow.M_UI_Glow"));
			UE_LOG(LogTemp, Log, TEXT("[T66Style] Load UI glow material -> %s"), GButtonGlowMaterial ? TEXT("OK") : TEXT("MISS"));
		}

		return GButtonGlowMaterial.Get();
	}

	static FLinearColor ResolveButtonGlowColor(ET66ButtonType ButtonType)
	{
		switch (ButtonType)
		{
		case ET66ButtonType::Danger:
			return FT66Style::Tokens::Danger;
		case ET66ButtonType::Success:
			return FT66Style::Tokens::Success;
		case ET66ButtonType::ToggleActive:
			return FT66Style::Tokens::Text;
		default:
			return FT66Style::Tokens::Border;
		}
	}

	static TSharedPtr<FT66ButtonGlowState> CreateButtonGlowState(ET66ButtonType ButtonType)
	{
		TSharedPtr<FT66ButtonGlowState> State = MakeShared<FT66ButtonGlowState>();
		State->Color = ResolveButtonGlowColor(ButtonType);

		if (UMaterialInterface* GlowMaterial = GetButtonGlowMaterial())
		{
			State->Material.Reset(UMaterialInstanceDynamic::Create(GlowMaterial, GetTransientPackage()));
			if (State->Material.IsValid())
			{
				State->Material->SetVectorParameterValue(TEXT("GlowColor"), State->Color);
				State->Material->SetScalarParameterValue(TEXT("GlowIntensity"), 0.f);

				State->Brush = MakeShared<FSlateBrush>();
				State->Brush->DrawAs = ESlateBrushDrawType::Image;
				State->Brush->Tiling = ESlateBrushTileType::NoTile;
				// Keep the glow brush from inflating button desired size; the overlay slot stretches it to the button bounds.
				State->Brush->ImageSize = FVector2D(1.f, 1.f);
				State->Brush->TintColor = FSlateColor(FLinearColor::White);
				State->Brush->SetResourceObject(State->Material.Get());
			}
		}

		return State;
	}

	static void SetButtonGlowIntensity(const TSharedPtr<FT66ButtonGlowState>& State, float NewIntensity)
	{
		if (!State.IsValid())
		{
			return;
		}

		State->Intensity = FMath::Max(0.f, NewIntensity);
		if (State->Material.IsValid())
		{
			State->Material->SetVectorParameterValue(TEXT("GlowColor"), State->Color);
			State->Material->SetScalarParameterValue(TEXT("GlowIntensity"), State->Intensity);
		}
	}

	static UTexture2D* GetPanelTexture()
	{
		return GPanelDark.Get();
	}

	static FSlateBrush MakePanelTextureBrush(UTexture2D* Tex)
	{
		FSlateBrush Brush;
		Brush.DrawAs = ESlateBrushDrawType::Box;   // 9-slice: corners preserved, center stretches
		Brush.Tiling = ESlateBrushTileType::NoTile;
		Brush.SetResourceObject(Tex);
		Brush.TintColor = FSlateColor(FLinearColor::White);
		Brush.ImageSize = FVector2D(128.f, 128.f);
		// Margin defines the 9-slice inset as fraction of image size.
		// 0.25 = 25% from each edge = 32px on a 128px texture, covering the corner/border region.
		Brush.Margin = FMargin(0.25f);
		return Brush;
	}

	static void LoadPanelTexturesOnce()
	{
		if (GPanelDark) return;
		auto Load = [](const TCHAR* Path) -> UTexture2D* {
			UTexture2D* T = LoadObject<UTexture2D>(nullptr, Path);
			UE_LOG(LogTemp, Log, TEXT("[T66Style] Load panel tex %s -> %s"), Path, T ? TEXT("OK") : TEXT("MISS"));
			return T;
		};
		GPanelDark  = Load(TEXT("/Game/UI/Assets/PanelDark.PanelDark"));
	}

	void ApplyThemePalette()
	{
		using T = FT66Style::Tokens;
		// Dark: pitch black panels, white text, white borders
		T::Bg          = FLinearColor(0.08f, 0.08f, 0.10f, 1.0f);
		T::Panel       = FLinearColor(0.0f, 0.0f, 0.0f, 1.0f);
		T::Panel2      = FLinearColor(0.0f, 0.0f, 0.0f, 1.0f);
		T::Stroke      = FLinearColor(0.18f, 0.18f, 0.20f, 1.0f);
		T::Scrim       = FLinearColor(0.0f, 0.0f, 0.0f, 0.70f);
		T::Text        = FLinearColor(1.0f, 1.0f, 1.0f, 1.0f);
		T::TextMuted   = FLinearColor(0.75f, 0.75f, 0.75f, 1.0f);
		T::Accent      = FLinearColor(0.0f, 0.0f, 0.0f, 1.0f);
		T::Accent2     = FLinearColor(0.0f, 0.0f, 0.0f, 1.0f);
		T::Danger      = FLinearColor(0.95f, 0.15f, 0.15f, 1.0f);
		T::Success     = FLinearColor(0.20f, 0.80f, 0.35f, 1.0f);
		T::Border      = FLinearColor(1.0f, 1.0f, 1.0f, 1.0f);
	}

	// ----- Font options: 0=Caesar Dressing, 1=Cinzel, 2=Cormorant SC, 3=Germania One, 4=Grenze, 5=Alagard, 6=Ransom -----
	static int32 GThemeFontIndex = 5;  // Alagard (default); cycle with T66NextFont console command
	static bool GForceBoldFont = false; // When true, use bold variant for all text (T66Bold console command)

	static const TCHAR* GThemeFontPaths[] = {
		TEXT("New Fonts/Caesar_Dressing/CaesarDressing-Regular.ttf"),   // 0 Caesar Dressing
		TEXT("New Fonts/Cinzel/static/Cinzel-Regular.ttf"),             // 1 Cinzel
		TEXT("New Fonts/Cormorant_SC/CormorantSC-Regular.ttf"),         // 2 Cormorant SC
		TEXT("New Fonts/Germania_One/GermaniaOne-Regular.ttf"),         // 3 Germania One
		TEXT("New Fonts/Grenze/Grenze-Regular.ttf"),                    // 4 Grenze
		TEXT("New Fonts/Alagard/alagard.ttf"),                         // 5 Alagard
		TEXT("New Fonts/Ransom/ransom.ttf"),                           // 6 Ransom
	};
	// Bold variant per font (nullptr = no bold asset, use Regular). Caesar Dressing, Germania One, Alagard, and Ransom have no bold.
	static const TCHAR* GThemeFontPathsBold[] = {
		nullptr,                                                       // 0 Caesar Dressing
		TEXT("New Fonts/Cinzel/static/Cinzel-Bold.ttf"),               // 1 Cinzel
		TEXT("New Fonts/Cormorant_SC/CormorantSC-Bold.ttf"),            // 2 Cormorant SC
		nullptr,                                                       // 3 Germania One
		TEXT("New Fonts/Grenze/Grenze-Bold.ttf"),                      // 4 Grenze
		nullptr,                                                       // 5 Alagard
		nullptr,                                                       // 6 Ransom
	};
	static const int32 GThemeFontCount = UE_ARRAY_COUNT(GThemeFontPaths);

	const FString& FontsDir()
	{
		static const FString Dir = FPaths::ProjectContentDir() / TEXT("Slate/Fonts");
		return Dir;
	}

	// Single TTF from Content/Slate/Fonts (path relative to FontsDir).
	FSlateFontInfo MakeFontFromFile(const TCHAR* RelativePath, int32 Size)
	{
		const FString Path = FontsDir() / RelativePath;
		if (!FPaths::FileExists(Path))
			return FCoreStyle::GetDefaultFontStyle(TEXT("Regular"), Size);
		TSharedPtr<const FCompositeFont> CompositeFont = MakeShared<FStandaloneCompositeFont>(
			NAME_None, Path, EFontHinting::Default, EFontLoadingPolicy::LazyLoad);
		return FSlateFontInfo(CompositeFont, static_cast<float>(Size));
	}

	// All UI font tokens use the selected font from GThemeFontPaths. Bold uses GThemeFontPathsBold when available.
	FSlateFontInfo ThemeFont(const TCHAR* Weight, int32 Size)
	{
		const int32 Idx = FMath::Clamp(GThemeFontIndex, 0, GThemeFontCount - 1);
		const bool bWantBold = GForceBoldFont || (FCString::Stricmp(Weight, TEXT("Bold")) == 0);
		const TCHAR* Path = GThemeFontPaths[Idx];
		if (bWantBold && GThemeFontPathsBold[Idx] != nullptr)
		{
			const FString BoldPath = FontsDir() / GThemeFontPathsBold[Idx];
			if (FPaths::FileExists(BoldPath))
				Path = GThemeFontPathsBold[Idx];
		}
		return MakeFontFromFile(Path, Size);
	}

	int32 AdvanceToNextFontIndex()
	{
		GThemeFontIndex = (GThemeFontIndex + 1) % GThemeFontCount;
		return GThemeFontIndex;
	}

	void ToggleForceBoldFont()
	{
		GForceBoldFont = !GForceBoldFont;
	}
}

// --- Font selection (all text uses the active font selection in this file) ---
FSlateFontInfo FT66Style::Tokens::FontRegular(int32 Size)
{
	return ThemeFont(TEXT("Regular"), Size);
}
FSlateFontInfo FT66Style::Tokens::FontBold(int32 Size)
{
	return ThemeFont(TEXT("Bold"), Size);
}
FSlateFontInfo FT66Style::Tokens::FontTitle()
{
	return ThemeFont(TEXT("Bold"), 52);
}
FSlateFontInfo FT66Style::Tokens::FontHeading()
{
	return ThemeFont(TEXT("Bold"), 24);
}
FSlateFontInfo FT66Style::Tokens::FontBody()
{
	return ThemeFont(TEXT("Regular"), 14);
}
FSlateFontInfo FT66Style::Tokens::FontSmall()
{
	return ThemeFont(TEXT("Regular"), 11);
}
FSlateFontInfo FT66Style::Tokens::FontChip()
{
	return ThemeFont(TEXT("Bold"), 11);
}
FSlateFontInfo FT66Style::Tokens::FontButton()
{
	return ThemeFont(TEXT("Bold"), 16);
}

void FT66Style::CycleToNextFont()
{
	AdvanceToNextFontIndex();
	if (StyleInstance.IsValid())
	{
		FSlateStyleRegistry::UnRegisterSlateStyle(*StyleInstance);
		RetainOldStyleSet(MoveTemp(StyleInstance));
	}
	Initialize();
}

void FT66Style::ToggleBoldFont()
{
	ToggleForceBoldFont();
	if (StyleInstance.IsValid())
	{
		FSlateStyleRegistry::UnRegisterSlateStyle(*StyleInstance);
		RetainOldStyleSet(MoveTemp(StyleInstance));
	}
	Initialize();
}

FName FT66Style::GetStyleSetName()
{
	static const FName Name(TEXT("T66Style"));
	return Name;
}

const ISlateStyle& FT66Style::Get()
{
	if (!StyleInstance.IsValid())
	{
		Initialize();
	}
	check(StyleInstance.IsValid());
	return *StyleInstance;
}

void FT66Style::Initialize()
{
	if (StyleInstance.IsValid())
	{
		return;
	}

	StyleInstance = MakeShared<FSlateStyleSet>(GetStyleSetName());
	ApplyThemePalette();

	// Load button textures once (dark set with bevel/gloss/border baked in).
	LoadButtonTexturesOnce();
	// Load panel texture once (9-slice for arbitrary panel sizes).
	LoadPanelTexturesOnce();

	bool bUseButtonTextures = HasButtonTextures();
	UTexture2D* BtnN = nullptr; UTexture2D* BtnH = nullptr; UTexture2D* BtnP = nullptr;
	if (bUseButtonTextures)
	{
		GetButtonTextures(BtnN, BtnH, BtnP);
	}

	bool bUsePanelTextures = GPanelTexturesAvailable();
	UTexture2D* PanelTex = bUsePanelTextures ? GetPanelTexture() : nullptr;

	UE_LOG(LogTemp, Log, TEXT("[T66Style] Resources: ButtonTex=%d  PanelTex=%d"),
		bUseButtonTextures ? 1 : 0, bUsePanelTextures ? 1 : 0);

	// Panel brushes: prefer texture (9-slice with baked border/bevel), fallback to rounded box
	const float BorderW = Tokens::BorderWidth;
	const FLinearColor BorderColor = Tokens::Border;

	if (bUsePanelTextures && PanelTex)
	{
		// Texture-backed panels: same texture for Bg, Panel, and Panel2 (all same visual treatment).
		// The panel texture has bevel/gloss/border baked in; white tint passes it through.
		FSlateBrush PanelBrush = MakePanelTextureBrush(PanelTex);
		StyleInstance->Set("T66.Brush.Bg",     new FSlateBrush(PanelBrush));
		StyleInstance->Set("T66.Brush.Panel",   new FSlateBrush(PanelBrush));
		StyleInstance->Set("T66.Brush.Panel2",  new FSlateBrush(PanelBrush));
	}
	else
	{
		// Fallback: solid rounded box with border
		StyleInstance->Set("T66.Brush.Bg",     new FSlateRoundedBoxBrush(Tokens::Bg, Tokens::CornerRadius, BorderColor, BorderW));
		StyleInstance->Set("T66.Brush.Panel",   new FSlateRoundedBoxBrush(Tokens::Panel, Tokens::CornerRadius, BorderColor, BorderW));
		StyleInstance->Set("T66.Brush.Panel2",  new FSlateRoundedBoxBrush(Tokens::Panel2, Tokens::CornerRadius, BorderColor, BorderW));
	}

	// Utility brushes (always procedural)
	StyleInstance->Set("T66.Brush.Stroke", new FSlateRoundedBoxBrush(Tokens::Stroke, Tokens::CornerRadiusSmall, BorderColor, BorderW));
	StyleInstance->Set("T66.Brush.Circle", new FSlateRoundedBoxBrush(FLinearColor::White, 110.f, BorderColor, BorderW));
	StyleInstance->Set("T66.Brush.Scrim",  new FSlateRoundedBoxBrush(Tokens::Scrim, 0.f));

	// Text styles
	{
		const FLinearColor Shadow(0.f, 0.f, 0.f, 0.85f);

		FTextBlockStyle Title = FTextBlockStyle()
			.SetFont(Tokens::FontTitle())
			.SetColorAndOpacity(Tokens::Text)
			.SetShadowOffset(FVector2D(1.f, 1.f))
			.SetShadowColorAndOpacity(Shadow);
		StyleInstance->Set("T66.Text.Title", Title);

		FTextBlockStyle Heading = FTextBlockStyle()
			.SetFont(Tokens::FontHeading())
			.SetColorAndOpacity(Tokens::Text)
			.SetShadowOffset(FVector2D(1.f, 1.f))
			.SetShadowColorAndOpacity(Shadow);
		StyleInstance->Set("T66.Text.Heading", Heading);

		FTextBlockStyle Body = FTextBlockStyle()
			.SetFont(Tokens::FontBody())
			.SetColorAndOpacity(Tokens::TextMuted);
		StyleInstance->Set("T66.Text.Body", Body);

		FTextBlockStyle Chip = FTextBlockStyle()
			.SetFont(Tokens::FontChip())
			.SetColorAndOpacity(Tokens::Text);
		StyleInstance->Set("T66.Text.Chip", Chip);

		FTextBlockStyle ButtonText = FTextBlockStyle()
			.SetFont(Tokens::FontButton())
			.SetColorAndOpacity(Tokens::Text);
		StyleInstance->Set("T66.Text.Button", ButtonText);
	}

	// Button styles: prefer 6-texture set (with effects baked in), else solid rounded box fallback
	{
		if (bUseButtonTextures && BtnN && BtnH && BtnP)
		{
			// Pre-rendered textures with bevel/gloss/border baked in. White tint = pass through.
			auto MakeTexStyle = [](UTexture2D* N, UTexture2D* H, UTexture2D* P) {
				return FButtonStyle()
					.SetNormal(MakeButtonTextureBrush(N))
					.SetHovered(MakeButtonTextureBrush(H))
					.SetPressed(MakeButtonTextureBrush(P))
					.SetNormalPadding(FT66Style::Tokens::ButtonPadding)
					.SetPressedPadding(FT66Style::Tokens::ButtonPaddingPressed);
			};
			StyleInstance->Set("T66.Button.Primary",      MakeTexStyle(BtnN, BtnH, BtnP));
			StyleInstance->Set("T66.Button.Neutral",      MakeTexStyle(BtnN, BtnH, BtnP));
			StyleInstance->Set("T66.Button.Danger",       MakeTexStyle(BtnN, BtnH, BtnP));
			StyleInstance->Set("T66.Button.ToggleActive", MakeTexStyle(BtnN, BtnH, BtnP));
		}
		else
		{
			// Fallback: solid rounded box with border (no texture needed)
			const FLinearColor NeutralN = Tokens::Panel2;
			const FLinearColor NeutralH = Tokens::Panel2 + FLinearColor(0.05f, 0.05f, 0.07f, 0.f);
			const FLinearColor NeutralP = Tokens::Panel2 + FLinearColor(0.08f, 0.08f, 0.10f, 0.f);

			auto MakeBoxStyle = [&](const FLinearColor& N, const FLinearColor& H, const FLinearColor& P) {
				return FButtonStyle()
					.SetNormal(FSlateRoundedBoxBrush(N, Tokens::CornerRadiusSmall, BorderColor, BorderW))
					.SetHovered(FSlateRoundedBoxBrush(H, Tokens::CornerRadiusSmall, BorderColor, BorderW))
					.SetPressed(FSlateRoundedBoxBrush(P, Tokens::CornerRadiusSmall, BorderColor, BorderW))
					.SetNormalPadding(Tokens::ButtonPadding)
					.SetPressedPadding(Tokens::ButtonPaddingPressed);
			};
			StyleInstance->Set("T66.Button.Primary",      MakeBoxStyle(NeutralN, NeutralH, NeutralP));
			StyleInstance->Set("T66.Button.Neutral",      MakeBoxStyle(NeutralN, NeutralH, NeutralP));
			StyleInstance->Set("T66.Button.Danger",       MakeBoxStyle(NeutralN, NeutralH, NeutralP));
			// ToggleActive: selected/pressed look — brighter fill + visible border so ON/OFF selection is obvious.
			{
				const FLinearColor ToggleN = Tokens::Text;
				const FLinearColor ToggleH = Tokens::Text * 0.90f + FLinearColor(0,0,0,0.10f);
				const FLinearColor ToggleP = Tokens::Text * 0.75f + FLinearColor(0,0,0,0.25f);
				const float ToggleBorderW = 2.f;
				const FLinearColor ToggleBorder = Tokens::Accent2.A > 0.01f ? Tokens::Accent2 : Tokens::Stroke;
				StyleInstance->Set("T66.Button.ToggleActive", FButtonStyle()
					.SetNormal(FSlateRoundedBoxBrush(ToggleN, Tokens::CornerRadiusSmall, ToggleBorder, ToggleBorderW))
					.SetHovered(FSlateRoundedBoxBrush(ToggleH, Tokens::CornerRadiusSmall, ToggleBorder, ToggleBorderW))
					.SetPressed(FSlateRoundedBoxBrush(ToggleP, Tokens::CornerRadiusSmall, ToggleBorder, ToggleBorderW))
					.SetNormalPadding(Tokens::ButtonPadding)
					.SetPressedPadding(Tokens::ButtonPaddingPressed));
			}
		}

		// Flat rectangular button body for custom border treatments like RetroWood.
		{
			const FSlateRoundedBoxBrush FlatBrush(FLinearColor::White, 0.f, FLinearColor::Transparent, 0.f);
			StyleInstance->Set("T66.Button.FlatRect", FButtonStyle()
				.SetNormal(FlatBrush)
				.SetHovered(FlatBrush)
				.SetPressed(FlatBrush)
				.SetNormalPadding(Tokens::ButtonPadding)
				.SetPressedPadding(Tokens::ButtonPaddingPressed));
		}

		// Transparent hit target for buttons that render their body from a separate fill overlay.
		{
			const FSlateRoundedBoxBrush FlatTransparentBrush(FLinearColor::Transparent, 0.f, FLinearColor::Transparent, 0.f);
			StyleInstance->Set("T66.Button.FlatTransparent", FButtonStyle()
				.SetNormal(FlatTransparentBrush)
				.SetHovered(FlatTransparentBrush)
				.SetPressed(FlatTransparentBrush)
				.SetNormalPadding(Tokens::ButtonPadding)
				.SetPressedPadding(Tokens::ButtonPaddingPressed));
		}

		// Row style: transparent background, very thin border, subtle hover highlight.
		// Used for leaderboard rows and list items that are clickable but shouldn't look like buttons.
		{
			constexpr float RowBorderW = 0.5f;
			const FLinearColor RowBorderColor = Tokens::Stroke;
			const FLinearColor RowN = FLinearColor(0.f, 0.f, 0.f, 0.f);       // transparent
			const FLinearColor RowH = Tokens::Stroke * FLinearColor(1,1,1,0.5f); // subtle highlight
			const FLinearColor RowP = Tokens::Stroke * FLinearColor(1,1,1,0.7f); // slightly stronger on press
			StyleInstance->Set("T66.Button.Row", FButtonStyle()
				.SetNormal(FSlateRoundedBoxBrush(RowN, 2.f, RowBorderColor, RowBorderW))
				.SetHovered(FSlateRoundedBoxBrush(RowH, 2.f, RowBorderColor, RowBorderW))
				.SetPressed(FSlateRoundedBoxBrush(RowP, 2.f, RowBorderColor, RowBorderW))
				.SetNormalPadding(FMargin(0.f))
				.SetPressedPadding(FMargin(0.f)));
		}

	}

	// Dropdown: use exactly the same button style as T66.Button.Neutral (texture or fallback) + small down arrow
	{
		FComboButtonStyle DropdownStyle;
		DropdownStyle.ButtonStyle = StyleInstance->GetWidgetStyle<FButtonStyle>("T66.Button.Neutral");
		FSlateBrush ArrowBrush = FCoreStyle::Get().GetWidgetStyle<FComboButtonStyle>("ComboButton").DownArrowImage;
		ArrowBrush.TintColor = FSlateColor(Tokens::Text);
		DropdownStyle.DownArrowImage = ArrowBrush;
		DropdownStyle.MenuBorderBrush = FSlateRoundedBoxBrush(Tokens::Panel, Tokens::CornerRadiusSmall, BorderColor, BorderW);
		DropdownStyle.MenuBorderPadding = FMargin(0.f);
		StyleInstance->Set("T66.Dropdown.ComboButtonStyle", DropdownStyle);
	}

	FSlateStyleRegistry::RegisterSlateStyle(*StyleInstance);

	static bool bConsoleRegistered = false;
	if (!bConsoleRegistered)
	{
		IConsoleManager::Get().RegisterConsoleCommand(
			TEXT("T66NextFont"),
			TEXT("Cycle to the next UI font (Caesar Dressing, Cinzel, Cormorant SC, Germania One, Grenze, Alagard, Ransom). Reopens style so new UI uses it."),
			FConsoleCommandDelegate::CreateStatic(&FT66Style::CycleToNextFont),
			ECVF_Default);
		IConsoleManager::Get().RegisterConsoleCommand(
			TEXT("T66Bold"),
			TEXT("Toggle force-bold: all UI text uses the bold variant of the current font (if the font has a bold asset)."),
			FConsoleCommandDelegate::CreateStatic(&FT66Style::ToggleBoldFont),
			ECVF_Default);
		bConsoleRegistered = true;
	}
}

FOnClicked FT66Style::DebounceClick(const FOnClicked& InnerDelegate)
{
	// Global timestamp shared by ALL debounced buttons.
	// Any click within 150 ms of the previous one is silently dropped.
	// 150 ms is imperceptible for intentional clicks but prevents:
	//   - double-fire from rapid/spam clicking
	//   - UI rebuild crashes from overlapping widget teardowns
	//   - accidental double-navigation
	return FOnClicked::CreateLambda([InnerDelegate]() -> FReply
	{
		static double GLastClickTime = 0.0;
		const double Now = FPlatformTime::Seconds();
		if (Now - GLastClickTime < 0.15)
		{
			return FReply::Handled();
		}
		GLastClickTime = Now;
		return InnerDelegate.Execute();
	});
}

ET66ButtonBorderVisual FT66Style::ResolveButtonBorderVisual(const FT66ButtonParams& Params)
{
	if (Params.BorderVisual != ET66ButtonBorderVisual::Default)
	{
		return Params.BorderVisual;
	}

	if (Params.Type == ET66ButtonType::Row)
	{
		return ET66ButtonBorderVisual::None;
	}

	return ET66ButtonBorderVisual::RetroWood;
}

ET66ButtonBackgroundVisual FT66Style::ResolveButtonBackgroundVisual(const FT66ButtonParams& Params)
{
	if (Params.BackgroundVisual != ET66ButtonBackgroundVisual::Default)
	{
		return Params.BackgroundVisual;
	}

	if (Params.Type == ET66ButtonType::Row)
	{
		return ET66ButtonBackgroundVisual::None;
	}

	return ET66ButtonBackgroundVisual::MainMenuArcane;
}

ET66ButtonBorderVisual FT66Style::ResolvePanelBorderVisual(const FT66PanelParams& Params)
{
	if (Params.BorderVisual != ET66ButtonBorderVisual::Default)
	{
		return Params.BorderVisual;
	}

	return Params.Type == ET66PanelType::Bg
		? ET66ButtonBorderVisual::None
		: ET66ButtonBorderVisual::RetroWood;
}

ET66ButtonBackgroundVisual FT66Style::ResolvePanelBackgroundVisual(const FT66PanelParams& Params)
{
	if (Params.BackgroundVisual != ET66ButtonBackgroundVisual::Default)
	{
		return Params.BackgroundVisual;
	}

	return ET66ButtonBackgroundVisual::MainMenuArcane;
}

float FT66Style::ResolveButtonDecorativeBorderThickness(const FT66ButtonParams& Params, int32 EffectiveFontSize, float MaxThickness)
{
	float Thickness = FMath::Clamp(static_cast<float>(EffectiveFontSize) * 0.25f, 3.5f, MaxThickness);

	if (Params.Height > 0.f)
	{
		Thickness = FMath::Min(Thickness, FMath::Max(3.f, Params.Height * 0.16f));
	}

	return FMath::Clamp(Thickness, 3.f, MaxThickness);
}

float FT66Style::ResolvePanelDecorativeBorderThickness(const FT66PanelParams& Params, float MaxThickness)
{
	switch (Params.Type)
	{
	case ET66PanelType::Bg:
		return 0.f;

	case ET66PanelType::Panel2:
		return FMath::Min(4.f, MaxThickness);

	case ET66PanelType::Panel:
	default:
		break;
	}

	const float MinPadding = FMath::Min(
		FMath::Min(Params.Padding.Left, Params.Padding.Top),
		FMath::Min(Params.Padding.Right, Params.Padding.Bottom));
	float Thickness = MaxThickness;
	if (MinPadding > 0.f)
	{
		Thickness = FMath::Min(Thickness, FMath::Max(4.f, MinPadding * 0.55f));
	}

	return FMath::Clamp(Thickness, 4.f, MaxThickness);
}

// ---------------------------------------------------------------------------
// Full params-based MakeButton — every button in the game funnels through here.
// ---------------------------------------------------------------------------
TSharedRef<SWidget> FT66Style::MakeButton(const FT66ButtonParams& Params)
{
	// 1. Resolve ButtonStyle name and default background color from Type.
	FName StyleName;
	FLinearColor DefaultBtnColor;
	switch (Params.Type)
	{
	case ET66ButtonType::Primary:
		StyleName = "T66.Button.Primary";    DefaultBtnColor = Tokens::Accent2; break;
	case ET66ButtonType::Danger:
		StyleName = "T66.Button.Danger";     DefaultBtnColor = Tokens::Danger;  break;
	case ET66ButtonType::Success:
		StyleName = "T66.Button.Primary";    DefaultBtnColor = Tokens::Success; break;
	case ET66ButtonType::ToggleActive:
		StyleName = "T66.Button.ToggleActive"; DefaultBtnColor = Tokens::Text;  break;
	case ET66ButtonType::Row:
		StyleName = "T66.Button.Row";        DefaultBtnColor = FLinearColor::Transparent; break;
	default: // Neutral
		StyleName = "T66.Button.Neutral";    DefaultBtnColor = Tokens::Panel2;  break;
	}

	const ET66ButtonBorderVisual ResolvedBorderVisual = ResolveButtonBorderVisual(Params);
	const ET66ButtonBackgroundVisual ResolvedBackgroundVisual = ResolveButtonBackgroundVisual(Params);

	const TSharedPtr<FT66ButtonFillBrushSet> FillBrushSet = FT66ButtonVisuals::CreateFillBrushSet(ResolvedBackgroundVisual);
	const bool bHasCustomFill = FillBrushSet.IsValid() && FillBrushSet->IsValid();

	if (ResolvedBorderVisual == ET66ButtonBorderVisual::RetroWood || ResolvedBorderVisual == ET66ButtonBorderVisual::MainMenuBlueTrim)
	{
		StyleName = bHasCustomFill ? "T66.Button.FlatTransparent" : "T66.Button.FlatRect";
	}

	const FButtonStyle& BtnStyle = Get().GetWidgetStyle<FButtonStyle>(StyleName);
	const FTextBlockStyle& TxtStyle = Get().GetWidgetStyle<FTextBlockStyle>("T66.Text.Button");

	// 2. Debounce the click delegate.
	FOnClicked SafeClick = DebounceClick(Params.OnClicked);

	// 3. Button background color.
	//    When a color override is set (e.g. ON/OFF toggle selected state), use it so the
	//    selected button is visually distinct. Otherwise with textures use white so the
	//    baked-in border/gloss passes through; with fallback use the style default.
	const bool bUsesTextureChrome =
		HasButtonTextures()
		&& ResolvedBorderVisual != ET66ButtonBorderVisual::RetroWood
		&& ResolvedBorderVisual != ET66ButtonBorderVisual::MainMenuBlueTrim;
	TAttribute<FSlateColor> BtnColor;
	if (bHasCustomFill)
	{
		BtnColor = TAttribute<FSlateColor>(FSlateColor(FLinearColor::White));
	}
	else if (Params.bHasColorOverride)
	{
		BtnColor = Params.ColorOverride;
	}
	else if (bUsesTextureChrome)
	{
		BtnColor = TAttribute<FSlateColor>(FSlateColor(FLinearColor::White));
	}
	else
	{
		BtnColor = TAttribute<FSlateColor>(FSlateColor(DefaultBtnColor));
	}

	// 4. Content padding (negative sentinel = don't override, use FMargin(0)).
	const FMargin ContentPad = (Params.Padding.Left >= 0.f) ? Params.Padding : FMargin(0.f);
	const TSharedPtr<ET66ButtonBorderState> BorderState = MakeShared<ET66ButtonBorderState>(ET66ButtonBorderState::Normal);

	// 5. Build the inner content widget (text block or custom).
	TAttribute<FText> TextAttr = Params.DynamicLabel.IsBound()
		? Params.DynamicLabel
		: TAttribute<FText>(Params.Label);

	FSlateFontInfo TextFont = (Params.FontSize > 0)
		? Tokens::FontBold(Params.FontSize)
		: TxtStyle.Font;

	TAttribute<FSlateColor> TextColor;
	if (Params.bHasStateTextColors)
	{
		const FSlateColor NormalStateTextColor = Params.NormalStateTextColor;
		const FSlateColor HoveredStateTextColor = Params.HoveredStateTextColor;
		const FSlateColor PressedStateTextColor = Params.PressedStateTextColor;
		TextColor = TAttribute<FSlateColor>::CreateLambda([BorderState, NormalStateTextColor, HoveredStateTextColor, PressedStateTextColor]() -> FSlateColor
		{
			if (!BorderState.IsValid())
			{
				return NormalStateTextColor;
			}

			switch (*BorderState)
			{
			case ET66ButtonBorderState::Hovered:
				return HoveredStateTextColor;
			case ET66ButtonBorderState::Pressed:
				return PressedStateTextColor;
			case ET66ButtonBorderState::Normal:
			default:
				return NormalStateTextColor;
			}
		});
	}
	else if (Params.bHasTextColorOverride)
	{
		TextColor = Params.TextColorOverride;
	}
	else
	{
		TextColor = TAttribute<FSlateColor>(TxtStyle.ColorAndOpacity);
	}

	TAttribute<FSlateColor> SecondaryTextColor;
	if (Params.bHasStateTextSecondaryColors)
	{
		const FSlateColor NormalStateTextSecondaryColor = Params.NormalStateTextSecondaryColor;
		const FSlateColor HoveredStateTextSecondaryColor = Params.HoveredStateTextSecondaryColor;
		const FSlateColor PressedStateTextSecondaryColor = Params.PressedStateTextSecondaryColor;
		SecondaryTextColor = TAttribute<FSlateColor>::CreateLambda([BorderState, NormalStateTextSecondaryColor, HoveredStateTextSecondaryColor, PressedStateTextSecondaryColor]() -> FSlateColor
		{
			if (!BorderState.IsValid())
			{
				return NormalStateTextSecondaryColor;
			}

			switch (*BorderState)
			{
			case ET66ButtonBorderState::Hovered:
				return HoveredStateTextSecondaryColor;
			case ET66ButtonBorderState::Pressed:
				return PressedStateTextSecondaryColor;
			case ET66ButtonBorderState::Normal:
			default:
				return NormalStateTextSecondaryColor;
			}
		});
	}

	TAttribute<FLinearColor> TextShadowColor;
	if (Params.bHasStateTextShadowColors)
	{
		const FLinearColor NormalStateTextShadowColor = Params.NormalStateTextShadowColor;
		const FLinearColor HoveredStateTextShadowColor = Params.HoveredStateTextShadowColor;
		const FLinearColor PressedStateTextShadowColor = Params.PressedStateTextShadowColor;
		TextShadowColor = TAttribute<FLinearColor>::CreateLambda([BorderState, NormalStateTextShadowColor, HoveredStateTextShadowColor, PressedStateTextShadowColor]() -> FLinearColor
		{
			if (!BorderState.IsValid())
			{
				return NormalStateTextShadowColor;
			}

			switch (*BorderState)
			{
			case ET66ButtonBorderState::Hovered:
				return HoveredStateTextShadowColor;
			case ET66ButtonBorderState::Pressed:
				return PressedStateTextShadowColor;
			case ET66ButtonBorderState::Normal:
			default:
				return NormalStateTextShadowColor;
			}
		});
	}
	else
	{
		TextShadowColor = TAttribute<FLinearColor>(TxtStyle.ShadowColorAndOpacity);
	}

	const TAttribute<FVector2D> TextShadowOffset = Params.bHasTextShadowOffset
		? TAttribute<FVector2D>(Params.TextShadowOffset)
		: TAttribute<FVector2D>(TxtStyle.ShadowOffset);

	const TSharedRef<SWidget> Content = [&]() -> TSharedRef<SWidget>
	{
		if (Params.CustomContent.IsValid())
		{
			return Params.CustomContent.ToSharedRef();
		}

		if (Params.bHasStateTextSecondaryColors)
		{
			const float PrimaryClipHeight = FMath::Max(1.f, FMath::RoundToFloat(static_cast<float>(TextFont.Size) * Params.TextDualToneSplit));

			return StaticCastSharedRef<SWidget>(
				SNew(SOverlay)
				+ SOverlay::Slot()
				[
					SNew(STextBlock)
					.Text(TextAttr)
					.Font(TextFont)
					.ColorAndOpacity(SecondaryTextColor)
					.Justification(ETextJustify::Center)
				]
				+ SOverlay::Slot()
				.VAlign(VAlign_Top)
				[
					SNew(SBox)
					.Clipping(EWidgetClipping::ClipToBounds)
					.HeightOverride(PrimaryClipHeight)
					[
						SNew(STextBlock)
						.Text(TextAttr)
						.Font(TextFont)
						.ColorAndOpacity(TextColor)
						.Justification(ETextJustify::Center)
					]
				]);
		}

		return StaticCastSharedRef<SWidget>(
			SNew(STextBlock)
			.Text(TextAttr)
			.Font(TextFont)
			.ColorAndOpacity(TextColor)
			.ShadowOffset(TextShadowOffset)
			.ShadowColorAndOpacity(TextShadowColor)
			.Justification(ETextJustify::Center)
		);
	}();

	// 6. Assemble: SBox > SButton > Content.
	//    Width/Height of 0 means "no constraint" (FOptionalSize() = unset).
	//    Row buttons use HAlign_Fill so custom content (e.g. column layouts) stretches to full width.
	const EHorizontalAlignment BtnHAlign = (Params.Type == ET66ButtonType::Row) ? HAlign_Fill : HAlign_Center;
	const EVerticalAlignment BtnVAlign = (Params.Type == ET66ButtonType::Row) ? VAlign_Fill : VAlign_Center;
	const TSharedPtr<FT66ButtonGlowState> GlowState = Params.bUseGlow ? CreateButtonGlowState(Params.Type) : nullptr;
	const TSharedPtr<FT66ButtonBorderBrushSet> BorderBrushSet = FT66ButtonVisuals::CreateBorderBrushSet(ResolvedBorderVisual);
	const int32 EffectiveFontSize = (Params.FontSize > 0) ? Params.FontSize : TextFont.Size;
	const float BorderThickness = (BorderBrushSet.IsValid() && BorderBrushSet->IsValid())
		? ResolveButtonDecorativeBorderThickness(Params, EffectiveFontSize, BorderBrushSet->Thickness)
		: 0.f;
	const auto SetGlow = [GlowState](float Intensity)
	{
		SetButtonGlowIntensity(GlowState, Intensity);
	};
	const auto SetBorderState = [BorderState](ET66ButtonBorderState NewState)
	{
		if (BorderState.IsValid())
		{
			*BorderState = NewState;
		}
	};

	if (ResolvedBorderVisual == ET66ButtonBorderVisual::RetroWood)
	{
		UE_LOG(LogTemp, Log, TEXT("[BORDER] MakeButton: Label='%s' BrushSet=%d BrushSetValid=%d Thickness=%.1f"),
			*Params.Label.ToString(),
			BorderBrushSet.IsValid() ? 1 : 0,
			(BorderBrushSet.IsValid() && BorderBrushSet->IsValid()) ? 1 : 0,
			BorderThickness);
	}

	const TSharedRef<SWidget> GlowWidget =
		!Params.bUseGlow
		? StaticCastSharedRef<SWidget>(
			SNew(SBox)
			.Visibility(EVisibility::Collapsed))
		: (GlowState.IsValid() && GlowState->Brush.IsValid())
			? StaticCastSharedRef<SWidget>(
				SNew(SImage)
				.Visibility(EVisibility::HitTestInvisible)
				.Image(TAttribute<const FSlateBrush*>::CreateLambda([GlowState]() -> const FSlateBrush*
				{
					return GlowState.IsValid() && GlowState->Brush.IsValid() ? GlowState->Brush.Get() : nullptr;
				})))
			: StaticCastSharedRef<SWidget>(
				SNew(SBorder)
				.Visibility(EVisibility::HitTestInvisible)
				.BorderImage(FCoreStyle::Get().GetBrush("WhiteBrush"))
				.BorderBackgroundColor(TAttribute<FSlateColor>::CreateLambda([GlowState]() -> FSlateColor
				{
					if (!GlowState.IsValid())
					{
						return FSlateColor(FLinearColor::Transparent);
					}

					FLinearColor Color = GlowState->Color;
					Color.A = GlowState->Intensity * Tokens::ButtonGlowFallbackOpacity;
					return FSlateColor(Color);
				})));

	const TAttribute<const FSlateBrush*> FillBrushAttr = TAttribute<const FSlateBrush*>::CreateLambda([FillBrushSet, BorderState]() -> const FSlateBrush*
	{
		if (!FillBrushSet.IsValid() || !FillBrushSet->IsValid() || !BorderState.IsValid())
		{
			return nullptr;
		}

		return FillBrushSet->GetBrush(*BorderState);
	});

	const TSharedRef<SWidget> FillWidget =
		bHasCustomFill
		? StaticCastSharedRef<SWidget>(
			SNew(SBorder)
			.Visibility(EVisibility::HitTestInvisible)
			.BorderImage(FillBrushAttr)
			.BorderBackgroundColor(FLinearColor::White))
		: StaticCastSharedRef<SWidget>(
			SNew(SBox)
			.Visibility(EVisibility::Collapsed));

	const TAttribute<const FSlateBrush*> HorizontalBorderBrushAttr = TAttribute<const FSlateBrush*>::CreateLambda([BorderBrushSet, BorderState]() -> const FSlateBrush*
	{
		if (!BorderBrushSet.IsValid() || !BorderState.IsValid())
		{
			return nullptr;
		}

		return BorderBrushSet->GetHorizontalBrush(*BorderState);
	});

	const TAttribute<const FSlateBrush*> VerticalBorderBrushAttr = TAttribute<const FSlateBrush*>::CreateLambda([BorderBrushSet, BorderState]() -> const FSlateBrush*
	{
		if (!BorderBrushSet.IsValid() || !BorderState.IsValid())
		{
			return nullptr;
		}

		return BorderBrushSet->GetVerticalBrush(*BorderState);
	});

	const TSharedRef<SWidget> BorderWidget =
		(BorderBrushSet.IsValid() && BorderBrushSet->IsValid() && BorderThickness > 0.f)
		? StaticCastSharedRef<SWidget>(
			SNew(SOverlay)
			.Visibility(EVisibility::HitTestInvisible)
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Top)
			[
				SNew(SBox)
				.HeightOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(HorizontalBorderBrushAttr)
				]
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Bottom)
			[
				SNew(SBox)
				.HeightOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(HorizontalBorderBrushAttr)
				]
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Left)
			.VAlign(VAlign_Fill)
			[
				SNew(SBox)
				.WidthOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(VerticalBorderBrushAttr)
				]
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Right)
			.VAlign(VAlign_Fill)
			[
				SNew(SBox)
				.WidthOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(VerticalBorderBrushAttr)
				]
			])
		: StaticCastSharedRef<SWidget>(
			SNew(SBox)
			.Visibility(EVisibility::Collapsed));

	return SNew(SBox)
		.MinDesiredWidth(Params.MinWidth > 0.f ? Params.MinWidth : FOptionalSize())
		.HeightOverride(Params.Height > 0.f ? Params.Height : FOptionalSize())
		.Visibility(Params.Visibility)
		[
			SNew(SOverlay)
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Fill)
			.Padding(FMargin(0.f))
			[
				GlowWidget
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Fill)
			.Padding(FMargin(0.f))
			[
				FillWidget
			]
			+ SOverlay::Slot()
			[
				SNew(SButton)
				.HAlign(BtnHAlign)
				.VAlign(BtnVAlign)
				.OnClicked(SafeClick)
				.OnHovered(FSimpleDelegate::CreateLambda([SetGlow, SetBorderState]() { SetGlow(Tokens::ButtonHoverGlowIntensity); SetBorderState(ET66ButtonBorderState::Hovered); }))
				.OnUnhovered(FSimpleDelegate::CreateLambda([SetGlow, SetBorderState]() { SetGlow(0.f); SetBorderState(ET66ButtonBorderState::Normal); }))
				.OnPressed(FSimpleDelegate::CreateLambda([SetGlow, SetBorderState]() { SetGlow(Tokens::ButtonPressedGlowIntensity); SetBorderState(ET66ButtonBorderState::Pressed); }))
				.OnReleased(FSimpleDelegate::CreateLambda([SetGlow, SetBorderState]() { SetGlow(Tokens::ButtonHoverGlowIntensity); SetBorderState(ET66ButtonBorderState::Hovered); }))
				.ButtonStyle(&BtnStyle)
				.ButtonColorAndOpacity(BtnColor)
				.ContentPadding(ContentPad)
				.IsEnabled(Params.IsEnabled)
				[
					Content
				]
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Fill)
			[
				BorderWidget
			]
		];
}

// ---------------------------------------------------------------------------
// Convenience overload — thin wrapper around the params version.
// ---------------------------------------------------------------------------
TSharedRef<SWidget> FT66Style::MakeButton(
	const FText& Label,
	FOnClicked OnClicked,
	ET66ButtonType Type,
	float MinWidth)
{
	FT66ButtonParams P(Label, MoveTemp(OnClicked), Type);
	P.MinWidth = MinWidth;
	return MakeButton(P);
}

// ---------------------------------------------------------------------------
// HasPanelTextures — public query so callers can check texture availability.
// ---------------------------------------------------------------------------
bool FT66Style::HasPanelTextures()
{
	return GPanelTexturesAvailable();
}

// ---------------------------------------------------------------------------
// Full params-based MakePanel — every panel in the game funnels through here.
// ---------------------------------------------------------------------------
TSharedRef<SWidget> FT66Style::MakePanel(
	const TSharedRef<SWidget>& Content,
	const FT66PanelParams& Params,
	TSharedPtr<SBorder>* OutBorder)
{
	// 1. Resolve brush name from panel type.
	FName BrushName;
	switch (Params.Type)
	{
	case ET66PanelType::Bg:     BrushName = "T66.Brush.Bg";     break;
	case ET66PanelType::Panel2: BrushName = "T66.Brush.Panel2"; break;
	default:                    BrushName = "T66.Brush.Panel";   break;
	}

	const ET66ButtonBorderVisual ResolvedBorderVisual = ResolvePanelBorderVisual(Params);
	const ET66ButtonBackgroundVisual ResolvedBackgroundVisual = ResolvePanelBackgroundVisual(Params);
	const TSharedPtr<FT66ButtonFillBrushSet> FillBrushSet = FT66ButtonVisuals::CreateFillBrushSet(ResolvedBackgroundVisual);
	const bool bHasCustomFill = FillBrushSet.IsValid() && FillBrushSet->IsValid();
	const TSharedPtr<FT66ButtonBorderBrushSet> BorderBrushSet = FT66ButtonVisuals::CreateBorderBrushSet(ResolvedBorderVisual);
	const float BorderThickness = (BorderBrushSet.IsValid() && BorderBrushSet->IsValid())
		? ResolvePanelDecorativeBorderThickness(Params, BorderBrushSet->Thickness)
		: 0.f;
	const bool bHasDecorativeBorder = BorderThickness > 0.f;

	// 2. Background color: when textures are loaded, use white tint to pass through
	//    the baked-in look. Color overrides only apply to the fallback path.
	TAttribute<FSlateColor> BgColor;
	if (bHasCustomFill)
	{
		BgColor = Params.bHasColorOverride
			? Params.ColorOverride
			: TAttribute<FSlateColor>(FSlateColor(FLinearColor::White));
	}
	else if (HasPanelTextures())
	{
		BgColor = TAttribute<FSlateColor>(FSlateColor(FLinearColor::White));
	}
	else if (Params.bHasColorOverride)
	{
		BgColor = Params.ColorOverride;
	}
	else
	{
		// Fallback: match the procedural brush tint to the token color.
		FLinearColor DefaultColor;
		switch (Params.Type)
		{
		case ET66PanelType::Bg:     DefaultColor = Tokens::Bg;     break;
		case ET66PanelType::Panel2: DefaultColor = Tokens::Panel2; break;
		default:                    DefaultColor = Tokens::Panel;   break;
		}
		BgColor = TAttribute<FSlateColor>(FSlateColor(DefaultColor));
	}

	const TAttribute<const FSlateBrush*> BackgroundBrushAttr = TAttribute<const FSlateBrush*>::CreateLambda([FillBrushSet, bHasCustomFill, BrushName]() -> const FSlateBrush*
	{
		if (bHasCustomFill && FillBrushSet.IsValid() && FillBrushSet->Normal.IsValid())
		{
			return FillBrushSet->Normal.Get();
		}

		return FT66Style::Get().GetBrush(BrushName);
	});

	const TAttribute<const FSlateBrush*> HorizontalBorderBrushAttr = TAttribute<const FSlateBrush*>::CreateLambda([BorderBrushSet]() -> const FSlateBrush*
	{
		if (!BorderBrushSet.IsValid())
		{
			return nullptr;
		}

		return BorderBrushSet->GetHorizontalBrush(ET66ButtonBorderState::Normal);
	});

	const TAttribute<const FSlateBrush*> VerticalBorderBrushAttr = TAttribute<const FSlateBrush*>::CreateLambda([BorderBrushSet]() -> const FSlateBrush*
	{
		if (!BorderBrushSet.IsValid())
		{
			return nullptr;
		}

		return BorderBrushSet->GetVerticalBrush(ET66ButtonBorderState::Normal);
	});

	const TSharedRef<SWidget> DecorativeBorderWidget =
		bHasDecorativeBorder
		? StaticCastSharedRef<SWidget>(
			SNew(SOverlay)
			.Visibility(EVisibility::HitTestInvisible)
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Top)
			[
				SNew(SBox)
				.HeightOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(HorizontalBorderBrushAttr)
				]
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Bottom)
			[
				SNew(SBox)
				.HeightOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(HorizontalBorderBrushAttr)
				]
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Left)
			.VAlign(VAlign_Fill)
			[
				SNew(SBox)
				.WidthOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(VerticalBorderBrushAttr)
				]
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Right)
			.VAlign(VAlign_Fill)
			[
				SNew(SBox)
				.WidthOverride(BorderThickness)
				[
					SNew(SImage)
					.Visibility(EVisibility::HitTestInvisible)
					.Image(VerticalBorderBrushAttr)
				]
			])
		: StaticCastSharedRef<SWidget>(
			SNew(SBox)
			.Visibility(EVisibility::Collapsed));

	const TSharedRef<SWidget> PanelChild =
		bHasDecorativeBorder
		? StaticCastSharedRef<SWidget>(
			SNew(SOverlay)
			+ SOverlay::Slot()
			.Padding(Params.Padding)
			[
				Content
			]
			+ SOverlay::Slot()
			.HAlign(HAlign_Fill)
			.VAlign(VAlign_Fill)
			[
				DecorativeBorderWidget
			])
		: Content;

	// 3. Build the SBorder.
	TSharedRef<SBorder> Border = SNew(SBorder)
		.BorderImage(BackgroundBrushAttr)
		.BorderBackgroundColor(BgColor)
		.Padding(bHasDecorativeBorder ? FMargin(0.f) : Params.Padding)
		.Visibility(Params.Visibility)
		[
			PanelChild
		];

	if (OutBorder)
	{
		*OutBorder = Border;
	}

	return Border;
}

// ---------------------------------------------------------------------------
// Convenience overload — panel type + padding only.
// ---------------------------------------------------------------------------
TSharedRef<SWidget> FT66Style::MakePanel(
	const TSharedRef<SWidget>& Content,
	ET66PanelType Type,
	FMargin Padding)
{
	return MakePanel(Content, FT66PanelParams(Type).SetPadding(Padding));
}

// ---------------------------------------------------------------------------
// GetDropdownComboButtonStyle — combo style for dropdowns.
// ---------------------------------------------------------------------------
const FComboButtonStyle& FT66Style::GetDropdownComboButtonStyle()
{
	return Get().GetWidgetStyle<FComboButtonStyle>("T66.Dropdown.ComboButtonStyle");
}

// ---------------------------------------------------------------------------
// MakeDropdown — dark-styled SComboButton.
// ---------------------------------------------------------------------------
TSharedRef<SWidget> FT66Style::MakeDropdown(const FT66DropdownParams& Params)
{
	const FComboButtonStyle& ComboStyle = GetDropdownComboButtonStyle();
	TSharedRef<SComboButton> Combo = SNew(SComboButton)
		.ComboButtonStyle(&ComboStyle)
		.OnGetMenuContent_Lambda([OnGet = Params.OnGetMenuContent]() { return OnGet(); })
		.ContentPadding(Params.Padding)
		.ButtonContent()
		[
			Params.Content
		];

	// Height 0 = no override: let the combo button size to its content so dropdowns aren't clipped.
	return SNew(SBox)
		.MinDesiredWidth(Params.MinWidth > 0.f ? Params.MinWidth : FOptionalSize())
		.HeightOverride(Params.Height > 0.f ? Params.Height : FOptionalSize())
		.Visibility(Params.Visibility)
		[
			Combo
		];
}

// ---------------------------------------------------------------------------
// DeferRebuild — safe, next-tick widget rebuild for any UUserWidget.
// ---------------------------------------------------------------------------
void FT66Style::DeferRebuild(UUserWidget* Widget, int32 ZOrder)
{
	if (!Widget) return;
	UWorld* World = Widget->GetWorld();
	if (!World) return;

	TWeakObjectPtr<UUserWidget> Weak(Widget);
	World->GetTimerManager().SetTimerForNextTick(
		FTimerDelegate::CreateLambda([Weak, ZOrder]()
		{
			UUserWidget* W = Weak.Get();
			if (!W || !W->GetCachedWidget().IsValid()) return;

			const bool bInViewport = W->IsInViewport();
			if (bInViewport) W->RemoveFromParent();

			W->ReleaseSlateResources(true);
			W->TakeWidget();

			if (bInViewport) W->AddToViewport(ZOrder);
		}));
}

void FT66Style::Shutdown()
{
	if (!StyleInstance.IsValid())
	{
		return;
	}

	FSlateStyleRegistry::UnRegisterSlateStyle(*StyleInstance);
	StyleInstance.Reset();
}
