// Copyright Tribulation 66. All Rights Reserved.

#include "Gameplay/T66SlashEffect.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "UObject/ConstructorHelpers.h"

AT66SlashEffect::AT66SlashEffect()
{
	PrimaryActorTick.bCanEverTick = true;
	InitialLifeSpan = 1.0f; // safety net — Tick calls Destroy() well before this

	DiscMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("DiscMesh"));
	RootComponent = DiscMesh;
	DiscMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	DiscMesh->CastShadow = false;

	// Engine cylinder: 100 units radius, 100 units half-height by default.
	static ConstructorHelpers::FObjectFinder<UStaticMesh> CylinderMesh(
		TEXT("/Engine/BasicShapes/Cylinder.Cylinder"));
	if (CylinderMesh.Succeeded())
	{
		DiscMesh->SetStaticMesh(CylinderMesh.Object);
	}

	// Load the translucent slash material (generated by Scripts/CreateSlashEffectMaterial.py).
	// Falls back to the engine default material if the asset hasn't been generated yet.
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> SlashMat(
		TEXT("/Game/VFX/M_SlashDisc.M_SlashDisc"));
	if (SlashMat.Succeeded())
	{
		SlashBaseMaterial = SlashMat.Object;
	}
}

void AT66SlashEffect::InitEffect(float InRadius, const FLinearColor& InColor)
{
	EffectRadius = FMath::Max(InRadius, 10.f);
	EffectColor = InColor;
}

void AT66SlashEffect::BeginPlay()
{
	Super::BeginPlay();

	// Scale the cylinder into a flat disc.
	// Engine cylinder radius = 50 units (diameter 100), half-height = 50 units.
	// We want XY = EffectRadius / 50 so the disc covers the right area.
	const float XY = EffectRadius / 50.f;
	const float Z = 0.02f; // almost flat
	DiscMesh->SetRelativeScale3D(FVector(XY, XY, Z));

	// Create dynamic material instance for runtime color/opacity control.
	if (SlashBaseMaterial)
	{
		MID = UMaterialInstanceDynamic::Create(SlashBaseMaterial, this);
		DiscMesh->SetMaterial(0, MID);
	}
	else
	{
		// Fallback: create MID from whatever material is on the mesh (engine default).
		MID = DiscMesh->CreateAndSetMaterialInstanceDynamic(0);
	}

	if (MID)
	{
		MID->SetVectorParameterValue(TEXT("Color"), EffectColor);
		MID->SetScalarParameterValue(TEXT("Opacity"), EffectColor.A);
	}
}

void AT66SlashEffect::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	Age += DeltaSeconds;
	const float Alpha = FMath::Clamp(1.f - (Age / Lifetime), 0.f, 1.f);

	if (Alpha <= 0.f)
	{
		Destroy();
		return;
	}

	// Slight scale-up over lifetime (expanding slash feel: 80% → 100% of target radius).
	if (DiscMesh)
	{
		const float Progress = FMath::Clamp(Age / Lifetime, 0.f, 1.f);
		const float XY = (EffectRadius / 50.f) * FMath::Lerp(0.8f, 1.0f, Progress);
		DiscMesh->SetRelativeScale3D(FVector(XY, XY, 0.02f));
	}

	// Fade out opacity.
	if (MID)
	{
		MID->SetScalarParameterValue(TEXT("Opacity"), EffectColor.A * Alpha);
		// Also dim the emissive color proportionally so it doesn't glow full-bright as it fades.
		FLinearColor FadedColor = EffectColor;
		FadedColor *= Alpha;
		FadedColor.A = 1.f; // Alpha channel in emissive is ignored; keep it at 1.
		MID->SetVectorParameterValue(TEXT("Color"), FadedColor);
	}
}
