// Copyright Tribulation 66. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "T66SlashEffect.generated.h"

class UStaticMeshComponent;
class UMaterialInstanceDynamic;
class UMaterialInterface;

/**
 * Short-lived visual effect for the AoE slash attack.
 * Spawned at the target's location, shows a flat translucent disc
 * that scales up slightly and fades out, then self-destructs.
 *
 * Material: /Game/VFX/M_SlashDisc (generated by Scripts/CreateSlashEffectMaterial.py).
 * C++ drives "Color" and "Opacity" parameters via MID.
 */
UCLASS(NotBlueprintable)
class T66_API AT66SlashEffect : public AActor
{
	GENERATED_BODY()

public:
	AT66SlashEffect();

	/** Call right after spawning to configure the visual. */
	void InitEffect(float InRadius, const FLinearColor& InColor);

protected:
	virtual void BeginPlay() override;
	virtual void Tick(float DeltaSeconds) override;

private:
	UPROPERTY(VisibleAnywhere)
	TObjectPtr<UStaticMeshComponent> DiscMesh;

	UPROPERTY(Transient)
	TObjectPtr<UMaterialInstanceDynamic> MID;

	/** Cached base material loaded from /Game/VFX/M_SlashDisc. */
	UPROPERTY()
	TObjectPtr<UMaterialInterface> SlashBaseMaterial;

	float EffectRadius = 300.f;
	FLinearColor EffectColor = FLinearColor(1.f, 0.3f, 0.1f, 0.8f);

	/** Total lifetime of the visual effect (seconds). */
	float Lifetime = 0.25f;

	/** Accumulated age since BeginPlay. */
	float Age = 0.f;
};
