// Copyright Zibra AI Inc 2025-2026. All Rights Reserved.

#include "ZibraRHI.h"

#define EXPAND_DEFINE_LOG_CATEGORY(CategoryName) DEFINE_LOG_CATEGORY(CategoryName)
EXPAND_DEFINE_LOG_CATEGORY(ZIBRA_RHI_MODULE_LOG);

#define EXPAND_IMPLEMENT_MODULE(ModuleImplClass, ModuleName) IMPLEMENT_MODULE(ModuleImplClass, ModuleName)
EXPAND_IMPLEMENT_MODULE(ZIBRA_RHI_MODULE_CLASSNAME, ZIBRA_RHI_MODULE_NAME)
