#ifndef ZIBRA_SHADER_COMMON
#define ZIBRA_SHADER_COMMON

#define BLOCK_SIZE_LOG2 3
#define BLOCK_SIZE (1 << 3)
#define TOTAL_BLOCK_SIZE (BLOCK_SIZE * BLOCK_SIZE * BLOCK_SIZE)
#define RENDER_PADDING_SIZE 1
#define RENDER_BLOCK_SIZE (BLOCK_SIZE + RENDER_PADDING_SIZE)
#define BINFO_POS 0
#define BINFO_OFFSET 1
#define BINFO_MASK 2
#define BINFO_COUNT 3

uint VoxelIndex(uint3 id)
{
    return id.z + (id.y + id.x * BLOCK_SIZE) * BLOCK_SIZE;
}

#endif
